### ISSUE TITLE
Include SORMAS-Stats into the next release.

### ISSUE THREAD

**Issue by JonasCir** [SORMAS-Foundation/SORMAS-Docker#415]
Hi there, 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/9091 is going to be in the next release.

The vhost config should be extend by the following:

```
         OIDCProviderMetadataURL http://local-keycloak:8080/keycloak/realms/SORMAS/.well-known/openid-configuration
         OIDCRedirectURI http://${SORMAS_SERVER_URL}/stats/secure
         OIDCClientSecret changeit
         OIDCCryptoPassphrase and-another-secret
         OIDCClientID sormas-stats
         <Location /stats>
               AuthType openid-connect
               Require claim resource_access.sormas-stats.roles:sormas-stats-access
               LogLevel debug
              ProxyPass  http://sormas-stats:3838 connectiontimeout=5 timeout=600
              ProxyPassReverse http://sormas-stats:3838
         </Location>
```

Please note that the `OIDCProviderMetadataURL` was taken from my local deployment, adjust as necessary for this project.

Further, the `RedirectMatch` needs to be extended by `stats`.

**Comment by JonasCir** [comment]
@fhauptmann @bernardsilenou @jwijffels

**Comment by bernardsilenou** [comment]
@jonasCir
Thanks Jonas!

**Comment by fhauptmann** [comment]
Contained in https://github.com/SORMAS-Foundation/SORMAS-Docker/pull/407 and https://github.com/SORMAS-Foundation/SORMAS-Docker/pull/439
