### ISSUE TITLE
Update Payara to version 6.x [0.5]

### ISSUE THREAD

**Issue by StefanKock** [SORMAS-Foundation/SORMAS-Docker#541]
In sync with https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12349, update Payara to latest 6.x version.

**Comment by fhauptmann** [comment]
Done

**Comment by StefanKock** [comment]
A assume the proposed task was not done, since /payara/Dockerfile still uses version 5 (checked on devops, development and master branches).
